### ISSUE TITLE
Click on unloaded block doesn't work

### ISSUE THREAD

**Issue by ineiti** [dedis/student_18_explorer#2]
Where: in graph view
Visible: genesis-block, some grey blocks, and a block with forward/backward links
What is supposed to happen: when I click on a grey block, it should load the links
What happens: nothing
Why: I'm using the new byzcoin which has a new structure:
```
net.Socket: new WebSocket(ws://192.168.0.1:7773/Skipchain/GetSingleBlockByIndex)
bundle.min.js:8 Uncaught Error: invalid wire type 6 at offset 1448
    at c.skipType (bundle.min.js:8)
    at y.SkipBlock$decode [as decode] (eval at i (bundle.min.js:62), <anonymous>:61:5)
    at WebSocket.a.onmessage (bundle.min.js:62)
```

**Comment by jeannechaverot** [comment]
It is a problem with the protobuf, and so should be an issue in the [@dedis/cothority](https://github.com/dedis/cothority) javascript package. These changes should not be incorporated into the js package until they are on master, right ?
